spring.application.name=unicorn-users

server.port=8082

#keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/unicorn_users
spring.security.oauth2.client.provider.keycloak.issuer-uri=htt://localhost:8080/realms/users
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username
spring.security.oauth2.client.registration.keycloak.client-id=456
spring.security.oauth2.client.registration.keycloak.client-secret=lno8z0d9HiUP3SuoL3HRKEsK2pF7hbHgAo6H4HPsxjmEx9RTQaYq4qjxsCXkWIcv59Zh9sb3y3EticqZQQh1if
spring.security.oauth2.client.registration.keycloak.scope[0]=openid
