spring.application.name=unicorn-users
server.port=8083

#keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8082/realms/unicorn_users
keycloak.base-url=http://localhost:8082
keycloak.realm=unicorn_users
keycloak.client-id=456
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}
